openapi: 3.0.0
info:
  title: EMBRAPA - Dados da Vitivinicultura
  description: This is a simple API for a FIAP - Tech Challenge
  contact:
    email: diogo.r.lessa@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
paths:
  /producao:
    get:
      summary: searches producao
      description: |
        By passing in the appropriate options, you can search for
        available producao info in the system
      operationId: search_producao
      parameters:
      - name: Produto_search_String
        in: query
        description: pass a product name search string for looking up producao
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: Ano_search_String
        in: query
        description: pass a year search string for looking up producao
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProducaoItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /processamento:
    get:
      summary: searches processamento
      description: |
        By passing in the appropriate options, you can search for
        available processamento info in the system
      operationId: search_processamento
      parameters:
      - name: Processamento_category_search_String
        in: query
        description: pass a category name search string for looking up processamento
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: Processamento_product_search_String
        in: query
        description: pass a product name search string for looking up processamento
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: Ano_search_String
        in: query
        description: pass a year search string for looking up processamento
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessamentoItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /comercializacao:
    get:
      summary: searches comercializacao
      description: |
        By passing in the appropriate options, you can search for
        available comercializacao info in the system
      operationId: search_comercializacao
      parameters:
      - name: Comercializacao_category_search_String
        in: query
        description: pass a category name search string for looking up comercializacao
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: Comercializacao_product_search_String
        in: query
        description: pass a product name search string for looking up comercializacao
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: Ano_search_String
        in: query
        description: pass a year search string for looking up comercializacao
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComercializacaoItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /importacao:
    get:
      summary: searches importacao
      description: |
        By passing in the appropriate options, you can search for
        available importacao info in the system
      operationId: search_importacao
      parameters:
      - name: Importacao_category_search_String
        in: query
        description: pass a category name search string for looking up importacao
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: Importacao_product_search_String
        in: query
        description: pass a product name search string for looking up importacao
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: Ano_search_String
        in: query
        description: pass a year search string for looking up importacao
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ImportacaoItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /exportacao:
    get:
      summary: searches exportacao
      description: |
        By passing in the appropriate options, you can search for
        available exportacao info in the system
      operationId: search_exportacao
      parameters:
      - name: Exportacao_category_search_String
        in: query
        description: pass a category name search string for looking up exportacao
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: Exportacao_product_search_String
        in: query
        description: pass a product name search string for looking up exportacao
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: Ano_search_String
        in: query
        description: pass a year search string for looking up exportacao
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExportacaoItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    ProducaoItem:
      required:
      - ano
      - produto
      - quantidade
      type: object
      properties:
        produto:
          type: string
          example: VINHO DE MESA
        ano:
          type: integer
          format: int32
          example: 1970
        quantidade:
          type: integer
          format: int32
          example: 217208604
      example:
        ano: 1970
        produto: VINHO DE MESA
        quantidade: 217208604
    ProcessamentoItem:
      required:
      - ano
      - categoria
      - cultivar
      - quantidade
      type: object
      properties:
        categoria:
          type: string
          example: TINTAS
        cultivar:
          type: string
          example: Carmenere
        ano:
          type: integer
          format: int32
          example: 1970
        quantidade:
          type: integer
          format: int32
          example: 1235
      example:
        ano: 1970
        cultivar: Carmenere
        categoria: TINTAS
        quantidade: 1235
    ComercializacaoItem:
      required:
      - ano
      - categoria
      - cultivar
      - quantidade
      type: object
      properties:
        categoria:
          type: string
          example: VINHO DE MESA
        cultivar:
          type: string
          example: Tinto
        ano:
          type: integer
          format: int32
          example: 1970
        quantidade:
          type: integer
          format: int32
          example: 83300735
      example:
        ano: 1970
        cultivar: Tinto
        categoria: VINHO DE MESA
        quantidade: 83300735
    ImportacaoItem:
      required:
      - ano
      - pais
      - quantidade
      - valor
      type: object
      properties:
        pais:
          type: string
          example: Chile
        ano:
          type: integer
          format: int32
          example: 1970
        quantidade:
          type: integer
          format: int32
          example: 162370
        valor:
          type: integer
          format: int32
          example: 101819
      example:
        ano: 1970
        valor: 101819
        quantidade: 162370
        pais: Chile
    ExportacaoItem:
      required:
      - ano
      - pais
      - quantidade
      - valor
      type: object
      properties:
        pais:
          type: string
          example: Estados Unidos
        ano:
          type: integer
          format: int32
          example: 1970
        quantidade:
          type: integer
          format: int32
          example: 11200
        valor:
          type: integer
          format: int32
          example: 4200
      example:
        ano: 1970
        valor: 4200
        quantidade: 11200
        pais: Estados Unidos

